// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhZhN__aGLdSxGUIO8_I6h2k4mRj_uC8',
    appId: '1:353252032802:web:ba270cc72fd726bdd1657b',
    messagingSenderId: '353252032802',
    projectId: 'manas-backend',
    authDomain: 'manas-backend.firebaseapp.com',
    storageBucket: 'manas-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmeQQ_VRCa4GE3B-M7gq_03oniOS9w5M',
    appId: '1:353252032802:android:98b2c899550d4d57d1657b',
    messagingSenderId: '353252032802',
    projectId: 'manas-backend',
    storageBucket: 'manas-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkdrq5k-cHJ1n-JJb_kgZdBhAckYUxrGs',
    appId: '1:353252032802:ios:63bb8e8527aa8651d1657b',
    messagingSenderId: '353252032802',
    projectId: 'manas-backend',
    storageBucket: 'manas-backend.firebasestorage.app',
    iosBundleId: 'com.example.manas',
  );
}
